const ClientConstants = {
  CREATE_REQUEST: 'CREATE_COURSE_REQUEST',
  CREATE_SUCCESS: 'CREATE_CLIENT_SUCCESS',
  CREATE_FAILURE: 'CREATE_CLIENT_FAILURE',

  GETALL_REQUEST: 'GETALL_CLIENT_REQUEST',
  GETALL_SUCCESS: 'GETALL_CLIENT_SUCCESS',
  GETALL_FAILURE: 'GETALL_CLIENT_FAILURE',

  GETBYID_REQUEST: 'GETBYID_CLIENT_REQUEST',
  GETBYID_SUCCESS: 'GETBYID_CLIENT_SUCCESS',
  GETBYID_FAILURE: 'GETBYID_CLIENT_FAILURE',

  SUBSCRIBE_REQUEST: 'SUBSCRIBE_CLIENT_REQUEST',
  SUBSCRIBE_SUCCESS: 'SUBSCRIBE_CLIENT_SUCCESS',
  SUBSCRIBE_FAILURE: 'SUBSCRIBE_CLIENT_FAILURE',

  DELETE_CLIENT_REQUEST: 'DELETE_CLIENT_REQUEST',
  DELETE_CLIENT_SUCCESS: 'DELETE_CLIENT_SUCCESS',
  DELETE_CLIENT_FAILURE: 'DELETE_CLIENT_FAILURE',
};

export default ClientConstants;
