const CourseConstants = {
  CREATE_REQUEST: 'CREATE_COURSE_REQUEST',
  CREATE_SUCCESS: 'CREATE_COURSE_SUCCESS',
  CREATE_FAILURE: 'CREATE_COURSE_FAILURE',

  GETALL_REQUEST: 'GETALL_COURSE_REQUEST',
  GETALL_SUCCESS: 'GETALL_COURSE_SUCCESS',
  GETALL_FAILURE: 'GETALL_COURSE_FAILURE',

  LOADCOURSE_REQUEST: 'LOADCOURSE_COURSE_REQUEST',
  LOADCOURSE_SUCCESS: 'LOADCOURSE_COURSE_SUCCESS',
  LOADCOURSE_FAILURE: 'LOADCOURSE_COURSE_FAILURE',
};

export default CourseConstants;
