const CourseConstants = {
  CREATE_REQUEST: "CREATE_COURSE_REQUEST",
  CREATE_SUCCESS: "CREATE_COURSE_SUCCESS",
  CREATE_FAILURE: "CREATE_COURSE_FAILURE",

  GETALL_REQUEST: "GETALL_COURSE_REQUEST",
  GETALL_SUCCESS: "GETALL_COURSE_SUCCESS",
  GETALL_FAILURE: "GETALL_COURSE_FAILURE"
};

export default CourseConstants;
