const CourseConstants = {
  CREATE_REQUEST: 'CREATE_COURSE_REQUEST',
  CREATE_SUCCESS: 'CREATE_COURSE_SUCCESS',
  CREATE_FAILURE: 'CREATE_COURSE_FAILURE',

  GETALL_REQUEST: 'GETALL_COURSE_REQUEST',
  GETALL_SUCCESS: 'GETALL_COURSE_SUCCESS',
  GETALL_FAILURE: 'GETALL_COURSE_FAILURE',

  GETUNSUBSCRIBED_REQUEST: 'GETUNSUBSCRIBED_COURSE_REQUEST',
  GETUNSUBSCRIBED_SUCCESS: 'GETUNSUBSCRIBED_COURSE_SUCCESS',
  GETUNSUBSCRIBED_FAILURE: 'GETUNSUBSCRIBED_COURSE_FAILURE',

  GETSUBSCRIBED_REQUEST: 'GETUNSUBSCRIBED_COURSE_REQUEST',
  GETSUBSCRIBED_SUCCESS: 'GETUNSUBSCRIBED_COURSE_SUCCESS',
  GETSUBSCRIBED_FAILURE: 'GETUNSUBSCRIBED_COURSE_FAILURE',

  DELETE_REQUEST: 'DELETE_COURSE_REQUEST',
  DELETE_SUCCESS: 'DELETE_COURSE_SUCCESS',
  DELETE_FAILURE: 'DELETE_COURSE_FAILURE',

  LOADCOURSE_REQUEST: 'LOADCOURSE_COURSE_REQUEST',
  LOADCOURSE_SUCCESS: 'LOADCOURSE_COURSE_SUCCESS',
  LOADCOURSE_FAILURE: 'LOADCOURSE_COURSE_FAILURE',

  EDIT_REQUEST: 'EDIT_COURSE_REQUEST',
  EDIT_SUCCESS: 'EDIT_COURSE_SUCCESS',
  EDIT_FAILURE: 'EDIT_COURSE_FAILURE',

  CLEAR_COURSES: 'CLEAR_COURSES',
};

export default CourseConstants;
