const ModuleConstants = {
  CREATE_REQUEST: 'CREATE_MODULE_REQUEST',
  CREATE_SUCCESS: 'CREATE_MODULE_SUCCESS',
  CREATE_FAILURE: 'CREATE_MODULE_FAILURE',

  OPENREDIRECTMODAL_REQUEST: 'OPEN_REDIRECTMODAL_MODULE_REQUEST',
  CLOSEREDIRECTMODAL_REQUEST: 'CLOSE_REDIRECTMODAL_MODULE_REQUEST',

  GETALL_REQUEST: 'GETALL_MODULE_REQUEST',
  GETALL_SUCCESS: 'GETALL_MODULE_SUCCESS',
  GETALL_FAILURE: 'GETALL_MODULE_FAILURE',

  UPLOAD_REQUEST: 'UPLOAD_MATERIAL_REQUEST',
  UPLOAD_SUCCESS: 'UPLOAD_MATERIAL_SUCCESS',
  UPLOAD_FAILURE: 'UPLOAD_MATERIAL_FAILURE',

  LOADMODULE_REQUEST: 'LOADMODULE_MODULE_REQUEST',
  LOADMODULE_SUCCESS: 'LOADMODULE_MODULE_SUCCESS',
  LOADMODULE_FAILURE: 'LOADMODULE_MODULE_FAILURE',

  DELETE_MODULE_REQUEST: 'DELETE_MODULE_REQUEST',
  DELETE_MODULE_SUCCESS: 'DELETE_MODULE_SUCCESS',
  DELETE_MODULE_FAILURE: 'DELETE_MODULE_FAILURE',

  CLEAR_MODULES: 'CLEAR_MODULES',

  MODULE_MATERIAL_REQUEST: 'MODULE_MATERIAL_MODULE_REQUEST',
  MODULE_MATERIAL_SUCCESS: 'MODULE_MATERIAL_MODULE_SUCCESS',
  MODULE_MATERIAL_FAILURE: 'MODULE_MATERIAL_MODULE_FAILURE',

  LOADTESTS_REQUEST: 'LOADTESTS_MODULE_REQUEST',
  LOADTESTS_SUCCESS: 'LOADTESTS_MODULE_SUCCESS',
  LOADTESTS_FAILURE: 'LOADTESTS_MODULE_FAILURE',

  LOAD_MODULE_REQUEST: 'LOAD_MODULE_REQUEST',
  LOAD_MODULE_SUCCESS: 'LOAD_MODULE_SUCCESS',
  LOAD_MODULE_FAILURE: 'LOAD_MODULE_FAILURE',

  EDIT_MODULE_REQUEST: 'EDIT_MODULE_REQUEST',
  EDIT_MODULE_SUCCESS: 'EDIT_MODULE_SUCCESS',
  EDIT_MODULE_FAILURE: 'EDIT_MODULE_FAILURE',

  GET_MATERIALS_REQUEST: 'GET_MATERIALS_REQUEST',
  GET_MATERIALS_SUCCESS: 'GET_MATERIALS_SUCCESS',
  GET_MATERIALS_FAILURE: 'GET_MATERIALS_FAILURE',
};

export default ModuleConstants;
