const ModuleConstants = {
  CREATE_REQUEST: 'CREATE_MODULE_REQUEST',
  CREATE_SUCCESS: 'CREATE_MODULE_SUCCESS',
  CREATE_FAILURE: 'CREATE_MODULE_FAILURE',

  GETALL_REQUEST: 'GETALL_MODULE_REQUEST',
  GETALL_SUCCESS: 'GETALL_MODULE_SUCCESS',
  GETALL_FAILURE: 'GETALL_MODULE_FAILURE',
};

export default ModuleConstants;
