const OptionConstants = {
  CREATE_REQUEST: 'CREATE_OPTION_REQUEST',
  CREATE_SUCCESS: 'CREATE_OPTION_SUCCESS',
  CREATE_FAILURE: 'CREATE_OPTION_FAILURE',

  GETALL_REQUEST: 'GETALL_OPTION_REQUEST',
  GETALL_SUCCESS: 'GETALL_OPTION_SUCCESS',
  GETALL_FAILURE: 'GETALL_OPTION_FAILURE',

  GETBYID_REQUEST: 'GETBYID_OPTION_REQUEST',
  GETBYID_SUCCESS: 'GETBYID_OPTION_SUCCESS',
  GETBYID_FAILURE: 'GETBYID_OPTION_FAILURE',
};

export default OptionConstants;
