const PaymentConstants = {

  GETALL_REQUEST: 'GETALL_PAYMENT_REQUEST',
  GETALL_SUCCESS: 'GETALL_PAYMENT_SUCCESS',
  GETALL_FAILURE: 'GETALL_PAYMENT_FAILURE',

  GETBYID_REQUEST: 'GETBYID_PAYMENT_REQUEST',
  GETBYID_SUCCESS: 'GETBYID_PAYMENT_SUCCESS',
  GETBYID_FAILURE: 'GETBYID_PAYMENT_FAILURE',
};

export default PaymentConstants;
