const PolicyConstants = {
  CREATE_REQUEST: 'CREATE_POLICY_REQUEST',
  CREATE_SUCCESS: 'CREATE_POLICY_SUCCESS',
  CREATE_FAILURE: 'CREATE_POLICY_FAILURE',

  GETALL_REQUEST: 'GETALL_POLICY_REQUEST',
  GETALL_SUCCESS: 'GETALL_POLICY_SUCCESS',
  GETALL_FAILURE: 'GETALL_POLICY_FAILURE',
};

export default PolicyConstants;
