const PolicyConstants = {
  CREATE_REQUEST: 'CREATE_POLICY_REQUEST',
  CREATE_SUCCESS: 'CREATE_POLICY_SUCCESS',
  CREATE_FAILURE: 'CREATE_POLICY_FAILURE',

  CREATE_ACKNOWLEDGEMENT_REQUEST: 'CREATE_ACKNOWLEDGEMENT_REQUEST',
  CREATE_ACKNOWLEDGEMENT_SUCCESS: 'CREATE_ACKNOWLEDGEMENT_SUCCESS',
  CREATE_ACKNOWLEDGEMENT_FAILURE: 'CREATE_ACKNOWLEDGEMENT_FAILURE',

  ACKNOWLEDGE_REQUEST: 'ACKNOWLEDGE_REQUEST',
  ACKNOWLEDGE_SUCCESS: 'ACKNOWLEDGE_SUCCESS',
  ACKNOWLEDGE_FAILURE: 'ACKNOWLEDGE_FAILURE',

  GETALL_REQUEST: 'GETALL_POLICY_REQUEST',
  GETALL_SUCCESS: 'GETALL_POLICY_SUCCESS',
  GETALL_FAILURE: 'GETALL_POLICY_FAILURE',

  GETCLIENTPOLICIES_REQUEST: 'GETCLIENT_POLICIES_REQUEST',
  GETCLIENTPOLICIES_SUCCESS: 'GETCLIENT_POLICIES_SUCCESS',
  GETCLIENTPOLICIES_FAILURE: 'GETCLIENT_POLICIES_FAILURE',

  GETOUTSTANDINGPOLICIESFORUSER_REQUEST:
    'GETOUTSTANDING_POLICIES_FORUSER_REQUEST',
  GETOUTSTANDINGPOLICIESFORUSER_SUCCESS:
    'GETOUTSTANDING_POLICIES_FORUSER_SUCCESS',
  GETOUTSTANDINGPOLICIESFORUSER_FAILURE:
    'GETOUTSTANDING_POLICIES_FORUSER_FAILURE',
  GETOUTSTANDINGPOLICIESFORCLIENT_REQUEST:
    'GETOUTSTANDING_POLICIES_FORCLIENT_REQUEST',
  GETOUTSTANDINGPOLICIESFORCLIENT_SUCCESS:
    'GETOUTSTANDING_POLICIES_FORCLIENT_SUCCESS',
  GETOUTSTANDINGPOLICIESFORCLIENT_FAILURE:
    'GETOUTSTANDING_POLICIES_FORCLIENT_FAILURE',

  GETPOLICY_REQUEST: 'DELETE_POLICY_REQUEST',
  GETPOLICY_SUCCESS: 'DELETE_POLICY_SUCCESS',
  GETPOLICY_FAILURE: 'DELETE_POLICY_FAILURE',

  EDITPOLICY_REQUEST: 'EDIT_POLICY_REQUEST',
  EDITPOLICY_SUCCESS: 'EDIT_POLICY_SUCCESS',
  EDITPOLICY_FAILURE: 'EDIT_POLICY_FAILURE',

  DELETEPOLICY_REQUEST: 'DELETE_POLICY_REQUEST',
  DELETEPOLICY_SUCCESS: 'DELETE_POLICY_SUCCESS',
  DELETEPOLICY_FAILURE: 'DELETE_POLICY_FAILURE',

  CLEAR_POLICIES: 'CLEAR_POLICIES',

  LOAD_POLICY_REQUEST: 'LOAD_POLICY_REQUEST',
  LOAD_POLICY_SUCCESS: 'LOAD_POLICY_SUCCESS',
  LOAD_POLICY_FAILURE: 'LOAD_POLICY_FAILURE',

  UPLOAD_MATERIAL_REQUEST: 'UPLOAD_MATERIAL_REQUEST',
  UPLOAD_MATERIAL_SUCCESS: 'UPLOAD_MATERIAL_SUCCESS',
  UPLOAD_MATERIAL_FAILURE: 'UPLOAD_MATERIAL_FAILURE',

  GET_MATERIAL_REQUEST: 'GET_MATERIAL_REQUEST',
  GET_MATERIAL_SUCCESS: 'GET_MATERIAL_SUCCESS',
  GET_MATERIAL_FAILURE: 'GET_MATERIAL_FAILURE',

  GET_MATERIALS_REQUEST: 'GET_MATERIALS_REQUEST',
  GET_MATERIALS_SUCCESS: 'GET_MATERIALS_SUCCESS',
  GET_MATERIALS_FAILURE: 'GET_MATERIALS_FAILURE',

  LOAD_MATERIAL_REQUEST: 'LOAD_MATERIAL_REQUEST',
  LOAD_MATERIAL_SUCCESS: 'LOAD_MATERIAL_SUCCESS',
  LOAD_MATERIAL_FAILURE: 'LOAD_MATERIAL_FAILURE',
};

export default PolicyConstants;
