const QuestionConstants = {
  CREATE_REQUEST: 'CREATE_MODULE_REQUEST',
  CREATE_SUCCESS: 'CREATE_QUESTION_SUCCESS',
  CREATE_FAILURE: 'CREATE_QUESTION_FAILURE',

  GETALL_REQUEST: 'GETALL_QUESTION_REQUEST',
  GETALL_SUCCESS: 'GETALL_QUESTION_SUCCESS',
  GETALL_FAILURE: 'GETALL_QUESTION_FAILURE',

  GETBYID_REQUEST: 'GETBYID_QUESTION_REQUEST',
  GETBYID_SUCCESS: 'GETBYID_QUESTION_SUCCESS',
  GETBYID_FAILURE: 'GETBYID_QUESTION_FAILURE',

  LOAD_QUESTIONS_REQUEST: 'LOAD_QUESTIONS_REQUEST',
  LOAD_QUESTIONS_SUCCESS: 'LOAD_QUESTIONS_SUCCESS',
  LOAD_QUESTIONS_FAILURE: 'LOAD_QUESTIONS_FAILURE',
};

export default QuestionConstants;
