const QuestionConstants = {
  CREATE_REQUEST: 'CREATE_MODULE_REQUEST',
  CREATE_SUCCESS: 'CREATE_QUESTION_SUCCESS',
  CREATE_FAILURE: 'CREATE_QUESTION_FAILURE',

  GETALL_REQUEST: 'GETALL_QUESTION_REQUEST',
  GETALL_SUCCESS: 'GETALL_QUESTION_SUCCESS',
  GETALL_FAILURE: 'GETALL_QUESTION_FAILURE',

  GETBYID_REQUEST: 'GETBYID_QUESTION_REQUEST',
  GETBYID_SUCCESS: 'GETBYID_QUESTION_SUCCESS',
  GETBYID_FAILURE: 'GETBYID_QUESTION_FAILURE',

  LOADQUESTIONS_REQUEST: 'LOAD_QUESTIONS_REQUEST',
  LOADQUESTIONS_SUCCESS: 'LOAD_QUESTIONS_SUCCESS',
  LOADQUESTIONS_FAILURE: 'LOAD_QUESTIONS_FAILURE',

  DELETE_REQUEST: 'DELETE_QUESTION_REQUEST',
  DELETE_SUCCESS: 'DELETE_QUESTION_SUCCESS',
  DELETE_FAILURE: 'DELETE_QUESTION_FAILURE',

  CLEAR_QUESTION: 'CLEAR_QUESTION',

  OPTIONS_REQUEST: 'QUESTION_OPTIONS_REQUEST',
  OPTIONS_SUCCESS: 'QUESTION_OPTIONS_SUCCESS',
  OPTIONS_FAILURE: 'QUESTION_OPTIONS_FAILURE',

  OPTIONS_ISANSWER_REQUEST: 'OPTIONS_ISANSWER_REQUEST',
  OPTIONS_ISANSWER_SUCCESS: 'OPTIONS_ISANSWER_SUCCESS',
  OPTIONS_ISANSWER_FAILURE: 'OPTIONS_ISANSWER_FAILURE',

  DELETE_QO_REQUEST: 'DELETE_QO_REQUEST',
  DELETE_QO_SUCCESS: 'DELETE_QO_SUCCESS',
  DELETE_QO_FAILURE: 'DELETE_QO_FAILURE',
};

export default QuestionConstants;
