const TestConstants = {
  CREATE_REQUEST: 'CREATE_TEST_REQUEST',
  CREATE_SUCCESS: 'CREATE_TEST_SUCCESS',
  CREATE_FAILURE: 'CREATE_TEST_FAILURE',

  GETALL_REQUEST: 'GETALL_TEST_REQUEST',
  GETALL_SUCCESS: 'GETALL_TEST_SUCCESS',
  GETALL_FAILURE: 'GETALL_TEST_FAILURE',

  LOADTEST_REQUEST: 'LOADTEST_TEST_REQUEST',
  LOADTEST_SUCCESS: 'LOADTEST_TEST_SUCCESS',
  LOADTEST_FAILURE: 'LOADTEST_TEST_FAILURE',

  LOADTESTQUESTIONS_REQUEST: 'LOADTESTQUESTIONS_TEST_REQUEST',
  LOADTESTQUESTIONS_SUCCESS: 'LOADTESTQUESTIONS_TEST_SUCCESS',
  LOADTESTQUESTIONS_FAILURE: 'LOADTESTQUESTIONS_TEST_FAILURE',
};

export default TestConstants;
