const TestConstants = {
  CREATE_REQUEST: 'CREATE_TEST_REQUEST',
  CREATE_SUCCESS: 'CREATE_TEST_SUCCESS',
  CREATE_FAILURE: 'CREATE_TEST_FAILURE',

  GETALL_REQUEST: 'GETALL_TEST_REQUEST',
  GETALL_SUCCESS: 'GETALL_TEST_SUCCESS',
  GETALL_FAILURE: 'GETALL_TEST_FAILURE',

  LOAD_TEST_REQUEST: 'LOAD_TEST_TEST_REQUEST',
  LOAD_TEST_SUCCESS: 'LOAD_TEST_TEST_SUCCESS',
  LOAD_TEST_FAILURE: 'LOAD_TEST_TEST_FAILURE',

  LOAD_TEST_QUESTIONS_REQUEST: 'LOAD_TEST_QUESTIONS_TEST_REQUEST',
  LOAD_TEST_QUESTIONS_SUCCESS: 'LOAD_TEST_QUESTIONS_TEST_SUCCESS',
  LOAD_TEST_QUESTIONS_FAILURE: 'LOAD_TEST_QUESTIONS_TEST_FAILURE',

  MARK_TEST_QUESTION_REQUEST: 'MARK_TEST_QUESTION_TEST_REQUEST',
  MARK_TEST_QUESTION_SUCCESS: 'MARK_TEST_QUESTION_TEST_SUCCESS',
  MARK_TEST_QUESTION_FAILURE: 'MARK_TEST_QUESTION_TEST_FAILURE',

  SUBMIT_TEST_REQUEST: 'SUBMIT_TEST_REQUEST',
  SUBMIT_TEST_SUCCESS: 'SUBMIT_TEST_SUCCESS',
  SUBMIT_TEST_FAILURE: 'SUBMIT_TEST_FAILURE',

  LOAD_QUESTION_SUCCESS: 'LOAD_QUESTION_TEST_SUCCESS',

  CHANGE_ANSWER: 'CHANGE_ANSWER_TEST_SUCCESS',

  LOAD_TEST_EDIT: 'LOAD_TEST_EDIT',
};

export default TestConstants;
