const TestConstants = {
  CREATE_REQUEST: 'CREATE_TEST_REQUEST',
  CREATE_SUCCESS: 'CREATE_TEST_SUCCESS',
  CREATE_FAILURE: 'CREATE_TEST_FAILURE',

  GETALL_REQUEST: 'GETALL_TEST_REQUEST',
  GETALL_SUCCESS: 'GETALL_TEST_SUCCESS',
  GETALL_FAILURE: 'GETALL_TEST_FAILURE',

  LOADTEST_REQUEST: 'LOADTEST_TEST_REQUEST',
  LOADTEST_SUCCESS: 'LOADTEST_TEST_SUCCESS',
  LOADTEST_FAILURE: 'LOADTEST_TEST_FAILURE',

  LOADTESTQUESTIONS_REQUEST: 'LOADTESTQUESTIONS_TEST_REQUEST',
  LOADTESTQUESTIONS_SUCCESS: 'LOADTESTQUESTIONS_TEST_SUCCESS',
  LOADTESTQUESTIONS_FAILURE: 'LOADTESTQUESTIONS_TEST_FAILURE',

  MARKTESTQUESTION_REQUEST: 'MARKTESTQUESTION_TEST_REQUEST',
  MARKTESTQUESTION_SUCCESS: 'MARKTESTQUESTION_TEST_SUCCESS',
  MARKTESTQUESTION_FAILURE: 'MARKTESTQUESTION_TEST_FAILURE',

  LOADQUESTION_SUCCESS: 'LOADQUESTION_TEST_SUCCESS',
  LOADQUESTION_SUCCES: 'LOADQUESTION_TEST_SUCCES',
  LOADQUESTION_SUCCE: 'LOADQUESTION_TEST_SUCCE',
};

export const test = {
  id: 4,
  name: 'Example Test',
  moduleID: 2,
  totalMarks: 100,
  module: null,
  questions: null,
  questionIds: null,
  enrolments: null,
};

export const questionsObj = [
  {
    id: 1,
    testId: 4,
    courseId: 2,
    userId: 2,
    score: 0,
    questionId: 2,
    marked: true,
    answerGivenId: 3,
    question: {
      title: 'Is this another sample?',
      allocatedMarks: 10,
      testId: 4,
      test: null,
      questionOptions: [
        {
          title: 'No it is not',
          isAnswer: false,
          questionId: 2,
          id: 3,
        },
        {
          title: 'Yes it is',
          isAnswer: true,
          questionId: 2,
          id: 4,
        },
      ],
      id: 2,
    },
    enrolmentTest: null,
    answerGiven: null,
  },
  {
    id: 2,
    testId: 4,
    courseId: 2,
    userId: 2,
    score: 10,
    questionId: 1,
    marked: true,
    answerGivenId: 1,
    question: {
      title: 'This is a sample?',
      allocatedMarks: 10,
      testId: 4,
      test: null,
      questionOptions: [
        {
          title: 'Yes it is',
          isAnswer: true,
          questionId: 1,
          id: 1,
        },
        {
          title: 'No it is not',
          isAnswer: false,
          questionId: 1,
          id: 2,
        },
      ],
      id: 1,
    },
    enrolmentTest: null,
    answerGiven: {
      title: 'Yes it is',
      isAnswer: true,
      questionId: 1,
      question: {
        title: 'This is a sample?',
        allocatedMarks: 10,
        testId: 4,
        test: null,
        questionOptions: [
          {
            title: 'No it is not',
            isAnswer: false,
            questionId: 1,
            id: 2,
          },
        ],
        id: 1,
      },
      id: 1,
    },
  },
  {
    id: 3,
    testId: 4,
    courseId: 2,
    userId: 2,
    score: 0,
    questionId: 2,
    marked: true,
    answerGivenId: 3,
    question: {
      title: 'Is this another sample?',
      allocatedMarks: 10,
      testId: 4,
      test: null,
      questionOptions: [
        {
          title: 'No it is not',
          isAnswer: false,
          questionId: 2,
          id: 3,
        },
        {
          title: 'Yes it is',
          isAnswer: true,
          questionId: 2,
          id: 4,
        },
      ],
      id: 2,
    },
    enrolmentTest: null,
    answerGiven: null,
  },
  {
    id: 4,
    testId: 4,
    courseId: 2,
    userId: 2,
    score: 10,
    questionId: 1,
    marked: true,
    answerGivenId: undefined,
    question: {
      title: 'This is a sample?',
      allocatedMarks: 10,
      testId: 4,
      test: null,
      questionOptions: [
        {
          title: 'Yes it is',
          isAnswer: true,
          questionId: 1,
          id: 1,
        },
        {
          title: 'No it is not',
          isAnswer: false,
          questionId: 1,
          id: 2,
        },
      ],
      id: 1,
    },
    enrolmentTest: null,
    answerGiven: {
      title: 'Yes it is',
      isAnswer: true,
      questionId: 1,
      question: {
        title: 'This is a sample?',
        allocatedMarks: 10,
        testId: 4,
        test: null,
        questionOptions: [
          {
            title: 'No it is not',
            isAnswer: false,
            questionId: 1,
            id: 2,
          },
        ],
        id: 1,
      },
      id: 1,
    },
  },
  {
    id: 5,
    testId: 4,
    courseId: 2,
    userId: 2,
    score: 0,
    questionId: 2,
    marked: true,
    answerGivenId: 3,
    question: {
      title: 'Is this another sample?',
      allocatedMarks: 10,
      testId: 4,
      test: null,
      questionOptions: [
        {
          title: 'No it is not',
          isAnswer: false,
          questionId: 2,
          id: 3,
        },
        {
          title: 'Yes it is',
          isAnswer: true,
          questionId: 2,
          id: 4,
        },
      ],
      id: 2,
    },
    enrolmentTest: null,
    answerGiven: null,
  },
  {
    id: 6,
    testId: 4,
    courseId: 2,
    userId: 2,
    score: 10,
    questionId: 1,
    marked: true,
    answerGivenId: undefined,
    question: {
      title: 'This is a sample?',
      allocatedMarks: 10,
      testId: 4,
      test: null,
      questionOptions: [
        {
          title: 'Yes it is',
          isAnswer: true,
          questionId: 1,
          id: 1,
        },
        {
          title: 'No it is not',
          isAnswer: false,
          questionId: 1,
          id: 2,
        },
      ],
      id: 1,
    },
    enrolmentTest: null,
    answerGiven: {
      title: 'Yes it is',
      isAnswer: true,
      questionId: 1,
      question: {
        title: 'This is a sample?',
        allocatedMarks: 10,
        testId: 4,
        test: null,
        questionOptions: [
          {
            title: 'No it is not',
            isAnswer: false,
            questionId: 1,
            id: 2,
          },
        ],
        id: 1,
      },
      id: 1,
    },
  },
];

export const question = {
  id: 2,
  testId: 4,
  courseId: 2,
  userId: 2,
  score: 0,
  questionId: 2,
  marked: true,
  answerGivenId: 3,
  question: {
    title: 'Is this another sample?',
    allocatedMarks: 10,
    testId: 4,
    test: null,
    questionOptions: [
      {
        title: 'No it is not',
        isAnswer: false,
        questionId: 2,
        id: 3,
      },
      {
        title: 'Yes it is',
        isAnswer: true,
        questionId: 2,
        id: 4,
      },
    ],
    id: 2,
  },
  enrolmentTest: null,
  answerGiven: null,
};

export default TestConstants;
